### ISSUE TITLE
When i run the pretrain.py in pytorch0.4 ,the best result (hits@10) of TransE model is about 10% .

### ISSUE THREAD

**Issue by xitongdashi** [cai-lw/KBGAN#3]
I don't know where come to wrong. However, with pytorch0.2 or 0.3v, the result is right w.r.t your paper. In fact , with only little change ,  your code will work with pytorch0.4 , but the result is not the same . I get confused. Might you help me ? I know this question is beyond your work , but i want to figure out the problem.

**Comment by cai-lw** [comment]
PyTorch changed its API significantly in version 0.4, so many API calls in the program can be affected. I am sorry that I cannot spot the problem, as problems could be everywhere.

Also, please note that I have no plan of updating this project for PyTorch 0.4 support.

**Comment by zqqQiu** [comment]
Pytorch0.3v also works fine?
