### ISSUE TITLE
有个keyError:(tensor(9738),tensor(85))的错误，在base_model.py中test_link函数

### ISSUE THREAD

**Issue by zhangyi85** [cai-lw/KBGAN#4]
这个错误指向test_link函数中第111行:
if tails[(s, r)]._nnz()>1
猜测是因为没有找到相应的尾节点key值而报错。
请帮忙解决一下，谢谢！

**Comment by zhangyi85** [comment]
我用的是torch 0.4.0

**Comment by cai-lw** [comment]
您好，这个项目暂时没有支持PyTorch的其他版本的计划
您可以改用README中指定的0.2.0版，或者尝试自己修改代码

**Comment by cai-lw** [comment]
之前有一位提issue的同学@xitongdashi 用PyTorch0.4稍微改了改跑起来了，你可以和他交流一下

**Comment by zhangyi85** [comment]
谢谢，换了0.2.0

**Comment by WeidongLi-KG** [comment]
@zhangyi85 https://github.com/WeidongLi-KG/KBGAN_PyTorch-v0.4.1

**Comment by WeidongLi-KG** [comment]
@zhangyi85 @cai-lw I have revised the KBGAN code with PyTorch-v0.4.1: https://github.com/WeidongLi-KG/KBGAN_PyTorch-v0.4.1
